import React, {FC} from "react";
import SideBar from "./components/SideBar";
import Head from "next/head";

type LayoutProps = {
    title: string;
    children: JSX.Element | JSX.Element[];
}
const Layout: FC<LayoutProps> = ({title, children}) => {
    return (
        <section className="h-screen font-poppins bg-gray-800 text-white h-screen flex flex-col justify-between">
            <Head>
                <title>{title} | HealthSake</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex h-screen">
                <SideBar/>
                <section className="w-4/5">{children}</section>
            </main>
        </section>
    );
};

export default Layout;
