import React, { FC } from "react";
import Head from "next/head";
import bg from "../../assets/gray.gif";
import Image from "next/image";
import stethoscope from "../../assets/icons/stethoscope.svg";
import Link from "next/link";

type LayoutProps = {
  title: string;
  children: JSX.Element | JSX.Element[];
};
const IntroLayout: FC<LayoutProps> = ({ title, children }) => {
  return (
    <section className="flex h-screen w-screen justify-end bg-gray-800 font-poppins text-white">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image alt={"background image"} src={bg} layout="fill" />
      <div className="z-10 flex h-screen flex-col justify-center gap-10 bg-gray-700 px-16 md:w-1/3 ">
        <Link href="/">
          <div>
            <Image src={stethoscope} alt="stethoscope" height={96} />
          </div>
        </Link>
        <main className="flex h-[70vh] flex-col gap-10 overflow-auto">
          {children}
        </main>
        <footer className="absolute bottom-4 right-0 w-full px-12 text-center text-xs text-gray-500 md:w-1/3">
          {" "}
          <span className="hover:cursor-help hover:text-gray-400">
            Developed with ❤️ by Jaideep Guntupalli (2020378), Cyrus Monteiro
            (2020368), Ayush Singhal (2020365) & Pranav Sharma (2020395)
          </span>
        </footer>
      </div>
    </section>
  );
};

export default IntroLayout;
