import React, {FC} from "react";
import Head from "next/head";
import bg from "../../assets/gray.gif";
import Image from "next/image";
import stethoscope from "../../assets/icons/stethoscope.svg";
import Link from "next/link";

type LayoutProps = {
    title: string;
    children: JSX.Element | JSX.Element[];
}
const IntroLayout: FC<LayoutProps> = ({title, children}) => {
    return (
        <section className="h-screen w-screen font-poppins bg-gray-800 text-white flex justify-end">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Image alt={"background image"} src={bg} layout="fill"/>
            <div
                className="bg-gray-700 md:w-1/3 px-16 flex flex-col gap-10 h-screen justify-center z-10">
                <Link href="/"><Image src={stethoscope} alt="stethoscope" height={96}/></Link>
                <main className="flex flex-col gap-10">{children}</main>
                <footer
                    className="text-xs text-gray-500 absolute bottom-4 w-full md:w-1/3 right-0 px-12 text-center"> <span
                    className="hover:text-gray-400 hover:cursor-help">Developed with ❤️ by Jaideep
                Guntupalli (2020378),
                Cyrus
                Monteiro (2020XXX), Ayush Singhal (2020XXX) &
                Pranav Sharma (2020XXX)</span>
                </footer>
            </div>
        </section>
    );
};

export default IntroLayout;
