import type {NextPage} from "next";
import React from "react";
import Head from "next/head";
import error from "@/assets/404.png"
import Image from "next/image";

const notFound: NextPage = () => {
    return (
        <section className="h-screen font-poppins bg-gray-800 text-white h-screen flex flex-col justify-between">
            <Head>
                <title>404 | Not Found | Healthsake</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex flex-col justify-center items-center h-screen gap-4">
                <div className="w-2/3 md:w-1/3"><Image alt={"404"} src={error}/></div>
                <h1 className="text-7xl font-bold text-gray-200">Oops</h1>
                <p className="text-lg font-medium text-gray-200">Something went wrong!</p>
            </main>
        </section>
    );
};

export default notFound;
